"""empty message

Revision ID: 47dbcd317120
Revises: 047108c860ba
Create Date: 2020-04-06 14:37:51.911694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dbcd317120'
down_revision = '047108c860ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('encrypted', sa.String(length=140), nullable=True))
    op.add_column('message', sa.Column('key', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'key')
    op.drop_column('message', 'encrypted')
    # ### end Alembic commands ###
