"""Hack successful field

Revision ID: 7bde7375abca
Revises: 8eb404e15276
Create Date: 2020-04-15 14:42:50.080747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bde7375abca'
down_revision = '8eb404e15276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hacker', sa.Column('successful', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hacker', 'successful')
    # ### end Alembic commands ###
