"""user hack counter

Revision ID: 84ced1f6834c
Revises: 7bde7375abca
Create Date: 2020-04-29 12:52:05.135201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ced1f6834c'
down_revision = '7bde7375abca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('successful_hacks', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('times_hacked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'times_hacked')
    op.drop_column('user', 'successful_hacks')
    # ### end Alembic commands ###
